language: scala
script: SCALA_VERSION=$SCALA_VERSION bash -x -c 'sbt ";set every scalaVersion := \"$SCALA_VERSION\"; test-only * -- -exclude testCommands --"'
scala:
  - "2.10.1"
  - "2.10.0"
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
services:
  - mongodb
